enableGlobalCache: true

npmRegistryServer: 'https://registry.npmmirror.com/'

# httpProxy: 'http://127.0.0.1:8889'

# httpsProxy: 'http://127.0.0.1:8889'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

progressBarStyle: patrick

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.js
