enableGlobalCache: true

# httpProxy: 'http://127.0.0.1:7890'

# httpsProxy: 'http://127.0.0.1:7890'

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

progressBarStyle: patrick

yarnPath: .yarn/releases/yarn-3.1.1.js
# nmHoistingLimits: workspaces

npmAuthToken: ${NPM_TOKEN}