enableGlobalCache: true

npmRegistryServer: "https://registry.npmmirror.com/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

progressBarStyle: patrick

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.js
