version: '3.7'
services:
  nacos:
    image: nacos/nacos-server:v2.0.4
    env_file:
      - ./nacos.env
    volumes:
      - mysql_logs:/home/nacos/logs
    ports:
      - '13324:8848'
      - '13325:9848'
      - '13326:9555'
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql
    

  mysql:
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - ./mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql_data:
  mysql_logs:
