apiVersion: v1
kind: Deployment
metadata:
  namespace: letscollab
  labels:
    version: v1
    app: letscollab
  name: demo-pod-v1
spec:
  # 建立的pods数量
  replicas: 2
  selector:
    matchLabels:
      version: v1
      # pod name
      app: demo
  template:
    metadata:
      labels:
        version: v1
        app: demo
    spec:
      containers:
        - name: nawb-demo
          image: nawb/demo
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-app
              protocol: TCP
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
      serviceAccount: default
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
