apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: demo-service
spec:
  sessionAffinity: ClientIP
  selector:
    app: demo
  type: NodePort
  ports:
    - name: http-app
      protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30001
