version: '3.7'

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:2.10.1-alpine
    restart: always
    volumes:
      - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - '13336:9000'
    networks:
      - apisix

  apisix:
    image: apache/apisix:2.11.0-alpine
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    #network_mode: host
    ports:
      - '10080:9080/tcp'
      - '10091:9091/tcp'
      - '10443:9443/tcp'
      - '10092:9092/tcp'
    networks:
      - apisix

  etcd:
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: 'true'
      ALLOW_NONE_AUTHENTICATION: 'yes'
      ETCD_ADVERTISE_CLIENT_URLS: 'http://0.0.0.0:2379'
      ETCD_LISTEN_CLIENT_URLS: 'http://0.0.0.0:2379'
    ports:
      - '2379:2379/tcp'
    networks:
      - apisix

  web1:
    image: nginx:1.21.5-alpine
    restart: always
    volumes:
      - ./upstream/web1.conf:/etc/nginx/nginx.conf
    ports:
      - '13332:80/tcp'
    environment:
      - NGINX_PORT=80
    networks:
      - apisix

  web2:
    image: nginx:1.21.5-alpine
    restart: always
    volumes:
      - ./upstream/web2.conf:/etc/nginx/nginx.conf
    ports:
      - '13333:80/tcp'
    environment:
      - NGINX_PORT=80
    networks:
      - apisix

  prometheus:
    image: prom/prometheus:v2.25.0
    restart: always
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '13334:9090'
    networks:
      - apisix

  grafana:
    image: grafana/grafana:7.3.7
    restart: always
    ports:
      - '13335:3000'
    volumes:
      - './grafana_conf/provisioning:/etc/grafana/provisioning'
      - './grafana_conf/dashboards:/var/lib/grafana/dashboards'
      - './grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini'
    networks:
      - apisix

networks:
  apisix:
    driver: overlay
    attachable: true

volumes:
  etcd_data:
    driver: local
